spring:
  application:
    name: project-admin
  # Datasource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-east.connect.psdb.cloud/project?sslMode=VERIFY_IDENTITY
    username: 5t6tq3hvlilkiwcollcd
    password: pscale_pw_KKyIzFh7CL2QDzU5x8ugxs7F7y1lpXMEvn4aSvBsco4
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
server:
  port: 8080
  error:
    include-message: always
springfox:
  documentation:
    swagger-ui:
      enabled: true

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/*
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /user/login
      - /user/register