server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: project-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.210.13:3306/XXXX
    username: XXXXXX
    password: XXXXXX
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20

springfox:
  documentation:
    swagger-ui:
      enabled: true

jwt:
  tokenHead: Bearer
  tokenHeader: Authorization
  secret: asdfgh
  expireTime: 86400
  justTime: 1800

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/*
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /user/login